### PR TITLE
Define implicit conversion for to_hash

### PR DESCRIPTION
**Pull request by sferik**

### CODE REVIEW

**Comment by sferik** [comment]
Thanks @coveralls, you piece of :shit:!

**Comment by avdi** [comment]
Yes. Hell yes. I think my only excuse for not doing this originally is that `#to_hash` didn't used to be an official Ruby thing.

**Comment by geori** [comment]
Thanks for the help!

**Comment by sferik** [comment]
@avdi I’d like to release Naught version 1.1.0, including this change. Any objections?

**Comment by avdi** [comment]
None at all!

**Pull request merged**
